package: vanilla
version: '0.0.1'
author: 'eaCe'

requires:
  redaxo: ^5.10.0
  php:
    version: '>=7.4'

installer_ignore:
  - node_modules
  - .git
  - .gitignore
  - .gitignore
  - .editorconfig
  - .eslintrc.js
  - package.json
  - yarn.lock
  - resources
  - webpack.mix.js
