name: ES Lint

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read

jobs:
  lint:

    runs-on: ubuntu-latest
    permissions:
      contents: write  # for Git to git apply

    steps:
      - uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install node modules
        run: |
          npm install

      - name: Run lint
        run: npx eslint ./assets/js/jquery-events-to-dom-events.js
